import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import MobileNavbar from "@/components/mobilni-nav";
import PageTransition from "@/components/PageTransition";
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: "GENIUS ELECTRO",
  description: "Generated by create next app",

  verification: {
    google: "HHBgB59LYahpmyXhoy3goIPXUM-_RpEjf5_Iip8tcyU",
    yandex: "b5260f808392311b",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Toaster
          position="top-center"
          reverseOrder={false}
          toastOptions={{
            duration: 4000,
          }}
        />
        <Navbar />
        <MobileNavbar />
        <PageTransition>
          {children}
        </PageTransition>
        <Footer />
      </body>
    </html>
  );
}
